-- MySQL Script generated by MySQL Workbench
-- Mon Dec 10 11:13:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema imdera
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema imdera
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imdera` DEFAULT CHARACTER SET latin1 ;
USE `imdera` ;

-- -----------------------------------------------------
-- Table `imdera`.`apoyoorganismosdeportivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`apoyoorganismosdeportivos` (
  `idApoyoOrganismosDeportivos` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreOrganismo` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `dia` VARCHAR(45) NULL DEFAULT NULL,
  `mes` VARCHAR(45) NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `lugar` VARCHAR(45) NULL DEFAULT NULL,
  `ceroACinco` VARCHAR(45) NULL DEFAULT NULL,
  `seisADoce` VARCHAR(45) NULL DEFAULT NULL,
  `treceADiecisiete` VARCHAR(45) NULL DEFAULT NULL,
  `dieciochoAVentiocho` VARCHAR(45) NULL DEFAULT NULL,
  `ventiochoMas` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idApoyoOrganismosDeportivos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`apoyoorganizacionescomunitarias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`apoyoorganizacionescomunitarias` (
  `idApoyoOrganizacionesComunitarias` INT(11) NOT NULL AUTO_INCREMENT,
  `barrio` VARCHAR(45) NULL DEFAULT NULL,
  `presidente` VARCHAR(45) NULL DEFAULT NULL,
  `apoyo` VARCHAR(45) NULL DEFAULT NULL,
  `mes` VARCHAR(45) NULL DEFAULT NULL,
  `dia` VARCHAR(45) NULL DEFAULT NULL,
  `comuna` VARCHAR(45) NULL DEFAULT NULL,
  `ceroACinco` VARCHAR(45) NULL DEFAULT NULL,
  `seisADoce` VARCHAR(45) NULL DEFAULT NULL,
  `treceADiecisiete` VARCHAR(45) NULL DEFAULT NULL,
  `dieciochoAVentiocho` VARCHAR(45) NULL DEFAULT NULL,
  `ventiochoMas` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idApoyoOrganizacionesComunitarias`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`apoyoseconomicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`apoyoseconomicos` (
  `idApoyosEconomicos` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `representante` VARCHAR(45) NULL DEFAULT NULL,
  `valorApoyado` VARCHAR(45) NULL DEFAULT NULL,
  `concepto` VARCHAR(200) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idApoyosEconomicos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`usuario` (
  `cedulaUsuario` VARCHAR(45) NOT NULL,
  `emailUsuario` VARCHAR(45) NULL DEFAULT NULL,
  `ContrasenaUsuario` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `tipoUsuario` VARCHAR(45) NULL DEFAULT NULL,
  `programa` VARCHAR(45) NULL DEFAULT NULL,
  `subprograma` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cedulaUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`ciclovia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`ciclovia` (
  `idCiclovia` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `sector` VARCHAR(45) NULL DEFAULT NULL,
  `mes` VARCHAR(45) NULL DEFAULT NULL,
  `dia` VARCHAR(45) NULL DEFAULT NULL,
  `ceroACinco` VARCHAR(45) NULL DEFAULT NULL,
  `seisADoce` VARCHAR(45) NULL DEFAULT NULL,
  `treceADiecisiete` VARCHAR(45) NULL DEFAULT NULL,
  `dieciochoAVentiocho` VARCHAR(45) NULL DEFAULT NULL,
  `VentiochoMas` VARCHAR(45) NULL DEFAULT NULL,
  `Usuario_cedulaUsuario` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idCiclovia`),
  INDEX `fk_Ciclovia_Usuario1_idx` (`Usuario_cedulaUsuario` ASC),
  CONSTRAINT `fk_Ciclovia_Usuario1`
    FOREIGN KEY (`Usuario_cedulaUsuario`)
    REFERENCES `imdera`.`usuario` (`cedulaUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`persona` (
  `documentoIdentidad` VARCHAR(45) NOT NULL,
  `nombreCompleto` VARCHAR(45) NULL DEFAULT NULL,
  `edad` INT(11) NULL DEFAULT NULL,
  `fechaNacimiento` DATE NULL DEFAULT NULL,
  `direccionDomicilio` VARCHAR(45) NULL DEFAULT NULL,
  `comuna` VARCHAR(45) NULL DEFAULT NULL,
  `estrato` VARCHAR(45) NULL DEFAULT NULL,
  `celular` VARCHAR(45) NULL DEFAULT NULL,
  `rh` VARCHAR(45) NULL DEFAULT NULL,
  `eps` VARCHAR(45) NULL DEFAULT NULL,
  `sisben` VARCHAR(45) NULL DEFAULT NULL,
  `telefonoFijo` VARCHAR(45) NULL DEFAULT NULL,
  `enfermedades` VARCHAR(45) NULL DEFAULT NULL,
  `medicamentos` VARCHAR(45) NULL DEFAULT NULL,
  `institucionEducativa` VARCHAR(45) NULL DEFAULT NULL,
  `jornada` VARCHAR(45) NULL DEFAULT NULL,
  `grado` VARCHAR(45) NULL DEFAULT NULL,
  `nombrePadre` VARCHAR(45) NULL DEFAULT NULL,
  `telefonoPadre` VARCHAR(45) NULL DEFAULT NULL,
  `nombreMadre` VARCHAR(45) NULL DEFAULT NULL,
  `telefonoMadre` VARCHAR(45) NULL DEFAULT NULL,
  `nombreAcudiente` VARCHAR(45) NULL DEFAULT NULL,
  `telefonoAcudiente` VARCHAR(45) NULL DEFAULT NULL,
  `acompañante` VARCHAR(45) NULL DEFAULT NULL,
  `telefonoAcompañante` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`documentoIdentidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`datosmorfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`datosmorfo` (
  `idDatosMorfo` INT(11) NOT NULL AUTO_INCREMENT,
  `estatura` VARCHAR(45) NULL DEFAULT NULL,
  `peso` VARCHAR(45) NULL DEFAULT NULL,
  `indiceMasaCorporal` VARCHAR(45) NULL DEFAULT NULL,
  `valoracionFuncional` VARCHAR(45) NULL DEFAULT NULL,
  `documentoPersona` VARCHAR(45) NOT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`idDatosMorfo`),
  INDEX `fk_DatosMorfo_Persona1_idx` (`documentoPersona` ASC),
  CONSTRAINT `fk_DatosMorfo_Persona1`
    FOREIGN KEY (`documentoPersona`)
    REFERENCES `imdera`.`persona` (`documentoIdentidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`deporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`deporte` (
  `idDeportes` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idDeportes`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`discapacidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`discapacidad` (
  `idDiscapacidad` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `Persona_documentoIdentidadPersona` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idDiscapacidad`),
  INDEX `fk_Discapacidad_Persona1_idx` (`Persona_documentoIdentidadPersona` ASC),
  CONSTRAINT `fk_Discapacidad_Persona1`
    FOREIGN KEY (`Persona_documentoIdentidadPersona`)
    REFERENCES `imdera`.`persona` (`documentoIdentidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`juegos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`juegos` (
  `idJuegos` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `Deporte_idDeportes` INT(11) NOT NULL,
  PRIMARY KEY (`idJuegos`, `Deporte_idDeportes`),
  INDEX `fk_Juegos_Deporte1_idx` (`Deporte_idDeportes` ASC),
  CONSTRAINT `fk_Juegos_Deporte1`
    FOREIGN KEY (`Deporte_idDeportes`)
    REFERENCES `imdera`.`deporte` (`idDeportes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`equipo` (
  `idEquipo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreEquipo` VARCHAR(45) NULL DEFAULT NULL,
  `treceADiecisiete` VARCHAR(45) NULL DEFAULT NULL,
  `dieciochoAVentiocho` VARCHAR(45) NULL DEFAULT NULL,
  `ventiochoMas` VARCHAR(45) NULL DEFAULT NULL,
  `Juegos_idJuegos` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idEquipo`),
  INDEX `fk_Equipo_Juegos1_idx` (`Juegos_idJuegos` ASC),
  CONSTRAINT `fk_Equipo_Juegos1`
    FOREIGN KEY (`Juegos_idJuegos`)
    REFERENCES `imdera`.`juegos` (`idJuegos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`escenario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`escenario` (
  `idEscenario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `tipoEscenario` VARCHAR(45) NULL DEFAULT NULL,
  `comuna` VARCHAR(45) NULL DEFAULT NULL,
  `claseEscenario` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idEscenario`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`escuelasdeportivas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`escuelasdeportivas` (
  `idEscuelasDeportivas` INT(11) GENERATED ALWAYS AS () VIRTUAL,
  `comuna` VARCHAR(45) NULL DEFAULT NULL,
  `nombreGrupo` VARCHAR(45) NULL DEFAULT NULL,
  `Deporte_idDeportes` INT(11) NULL DEFAULT NULL,
  `Escenario_idEscenario` INT(11) NULL DEFAULT NULL,
  `Usuario_cedulaUsuario` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idEscuelasDeportivas`),
  INDEX `fk_EscuelasDeportivas_Deporte1_idx` (`Deporte_idDeportes` ASC),
  INDEX `fk_EscuelasDeportivas_Escenario1_idx` (`Escenario_idEscenario` ASC),
  INDEX `fk_EscuelasDeportivas_Usuario1_idx` (`Usuario_cedulaUsuario` ASC),
  CONSTRAINT `fk_EscuelasDeportivas_Deporte1`
    FOREIGN KEY (`Deporte_idDeportes`)
    REFERENCES `imdera`.`deporte` (`idDeportes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EscuelasDeportivas_Escenario1`
    FOREIGN KEY (`Escenario_idEscenario`)
    REFERENCES `imdera`.`escenario` (`idEscenario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EscuelasDeportivas_Usuario1`
    FOREIGN KEY (`Usuario_cedulaUsuario`)
    REFERENCES `imdera`.`usuario` (`cedulaUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`escuelasdeportivas_has_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`escuelasdeportivas_has_persona` (
  `EscuelasDeportivas_idEscuelasDeportivas` INT(11) NOT NULL,
  `Persona_documentoIdentidadPersona` VARCHAR(45) NOT NULL,
  `tipoPersona` VARCHAR(45) NULL DEFAULT NULL,
  `fechaRegistro` DATE NULL,
  PRIMARY KEY (`EscuelasDeportivas_idEscuelasDeportivas`, `Persona_documentoIdentidadPersona`),
  INDEX `fk_EscuelasDeportivas_has_Persona_Persona1_idx` (`Persona_documentoIdentidadPersona` ASC),
  INDEX `fk_EscuelasDeportivas_has_Persona_EscuelasDeportivas1_idx` (`EscuelasDeportivas_idEscuelasDeportivas` ASC),
  CONSTRAINT `fk_EscuelasDeportivas_has_Persona_EscuelasDeportivas1`
    FOREIGN KEY (`EscuelasDeportivas_idEscuelasDeportivas`)
    REFERENCES `imdera`.`escuelasdeportivas` (`idEscuelasDeportivas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EscuelasDeportivas_has_Persona_Persona1`
    FOREIGN KEY (`Persona_documentoIdentidadPersona`)
    REFERENCES `imdera`.`persona` (`documentoIdentidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`eventosrecreando`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`eventosrecreando` (
  `idEventosRecreando` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreOrganizacion` VARCHAR(45) NULL DEFAULT NULL,
  `sitio` VARCHAR(45) NULL DEFAULT NULL,
  `mes` VARCHAR(45) NULL DEFAULT NULL,
  `dia` VARCHAR(50) NULL DEFAULT NULL,
  `comuna` VARCHAR(45) NULL DEFAULT NULL,
  `ano` VARCHAR(45) NULL DEFAULT NULL,
  `ceroACinco` VARCHAR(45) NULL DEFAULT NULL,
  `seisADoce` VARCHAR(45) NULL DEFAULT NULL,
  `treceADiecisiete` VARCHAR(45) NULL DEFAULT NULL,
  `dieciochoAVentiocho` VARCHAR(45) NULL DEFAULT NULL,
  `ventiochoMas` VARCHAR(45) NULL DEFAULT NULL,
  `tipoEvento` VARCHAR(45) NULL,
  PRIMARY KEY (`idEventosRecreando`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`gruposrecreando`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`gruposrecreando` (
  `idGruposRecreando` INT(11) NOT NULL AUTO_INCREMENT,
  `tipoGrupo` VARCHAR(45) NULL DEFAULT NULL,
  `nombreGrupo` VARCHAR(45) NULL DEFAULT NULL,
  `sitio` VARCHAR(100) NULL DEFAULT NULL,
  `dia` VARCHAR(100) NULL DEFAULT NULL,
  `comuna` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `claseGrupo` VARCHAR(45) NULL DEFAULT NULL,
  `Usuario_cedulaUsuario` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idGruposRecreando`),
  INDEX `fk_GruposRecreando_Usuario1_idx` (`Usuario_cedulaUsuario` ASC),
  CONSTRAINT `fk_GruposRecreando_Usuario1`
    FOREIGN KEY (`Usuario_cedulaUsuario`)
    REFERENCES `imdera`.`usuario` (`cedulaUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`gruposrecreando_has_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`gruposrecreando_has_persona` (
  `GruposRecreando_idGruposRecreando` INT(11) NOT NULL,
  `Persona_documentoIdentidadPersona` VARCHAR(45) NOT NULL,
  `fechaRegistro` DATE NULL DEFAULT NULL,
  `tipoPersona` VARCHAR(45) NULL,
  PRIMARY KEY (`GruposRecreando_idGruposRecreando`, `Persona_documentoIdentidadPersona`),
  INDEX `fk_GruposRecreando_has_Persona_Persona1_idx` (`Persona_documentoIdentidadPersona` ASC),
  INDEX `fk_GruposRecreando_has_Persona_GruposRecreando1_idx` (`GruposRecreando_idGruposRecreando` ASC),
  CONSTRAINT `fk_GruposRecreando_has_Persona_GruposRecreando1`
    FOREIGN KEY (`GruposRecreando_idGruposRecreando`)
    REFERENCES `imdera`.`gruposrecreando` (`idGruposRecreando`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GruposRecreando_has_Persona_Persona1`
    FOREIGN KEY (`Persona_documentoIdentidadPersona`)
    REFERENCES `imdera`.`persona` (`documentoIdentidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`habitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`habitos` (
  `idHabitos` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreGrupo` VARCHAR(45) NULL DEFAULT NULL,
  `tipoGrupo` VARCHAR(45) NULL DEFAULT NULL,
  `sitio` VARCHAR(100) NULL DEFAULT NULL,
  `dias` VARCHAR(100) NULL DEFAULT NULL,
  `hora` VARCHAR(100) NULL DEFAULT NULL,
  `comuna` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `Usuario_cedulaUsuario` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idHabitos`),
  INDEX `fk_Habitos_Usuario1_idx` (`Usuario_cedulaUsuario` ASC),
  CONSTRAINT `fk_Habitos_Usuario1`
    FOREIGN KEY (`Usuario_cedulaUsuario`)
    REFERENCES `imdera`.`usuario` (`cedulaUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`habitos_has_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`habitos_has_persona` (
  `Habito` INT(11) NOT NULL,
  `Persona` VARCHAR(45) NOT NULL,
  `tipoPersona` VARCHAR(45) NULL,
  `fechaRegistro` DATE NULL,
  PRIMARY KEY (`Habito`, `Persona`),
  INDEX `fk_Habitos_has_Persona_Persona1_idx` (`Persona` ASC),
  INDEX `fk_Habitos_has_Persona_Habitos1_idx` (`Habito` ASC),
  CONSTRAINT `fk_Habitos_has_Persona_Habitos1`
    FOREIGN KEY (`Habito`)
    REFERENCES `imdera`.`habitos` (`idHabitos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Habitos_has_Persona_Persona1`
    FOREIGN KEY (`Persona`)
    REFERENCES `imdera`.`persona` (`documentoIdentidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`mantenimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`mantenimiento` (
  `idMantenimiento` INT(11) NOT NULL AUTO_INCREMENT,
  `Actividad` VARCHAR(200) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `Escenario_idEscenario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idMantenimiento`),
  INDEX `fk_Mantenimiento_Escenario1_idx` (`Escenario_idEscenario` ASC),
  CONSTRAINT `fk_Mantenimiento_Escenario1`
    FOREIGN KEY (`Escenario_idEscenario`)
    REFERENCES `imdera`.`escenario` (`idEscenario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`prestamoescenarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`prestamoescenarios` (
  `idPrestamoEscenarios` INT(11) NOT NULL AUTO_INCREMENT,
  `Deporte_idDeportes` INT(11) NULL DEFAULT NULL,
  `Escenario_idEscenario` INT(11) NULL DEFAULT NULL,
  `organizacion` VARCHAR(45) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `ceroACinco` VARCHAR(45) NULL,
  `seisADoce` VARCHAR(45) NULL,
  `treceADiecisiete` VARCHAR(45) NULL,
  `dieciochoAVentiocho` VARCHAR(45) NULL,
  `ventiochoMas` VARCHAR(45) NULL,
  PRIMARY KEY (`idPrestamoEscenarios`),
  INDEX `fk_PrestamoEscenarios_Deporte1_idx` (`Deporte_idDeportes` ASC),
  INDEX `fk_PrestamoEscenarios_Escenario1_idx` (`Escenario_idEscenario` ASC),
  CONSTRAINT `fk_PrestamoEscenarios_Deporte1`
    FOREIGN KEY (`Deporte_idDeportes`)
    REFERENCES `imdera`.`deporte` (`idDeportes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PrestamoEscenarios_Escenario1`
    FOREIGN KEY (`Escenario_idEscenario`)
    REFERENCES `imdera`.`escenario` (`idEscenario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`puntosactividadfisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`puntosactividadfisica` (
  `idPuntosActividadFisica` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `lugar` VARCHAR(45) NULL DEFAULT NULL,
  `dias` VARCHAR(45) NULL DEFAULT NULL,
  `ceroACinco` VARCHAR(45) NULL DEFAULT NULL,
  `seisADoce` VARCHAR(45) NULL DEFAULT NULL,
  `treceADiecisiete` VARCHAR(45) NULL DEFAULT NULL,
  `dieciochoAVentiocho` VARCHAR(45) NULL DEFAULT NULL,
  `ventiochoMas` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idPuntosActividadFisica`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`superateintercolegiados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`superateintercolegiados` (
  `idsuperateIntercolegiados` INT(11) NOT NULL AUTO_INCREMENT,
  `ceroACinco` VARCHAR(45) NULL DEFAULT NULL,
  `seisADoce` VARCHAR(45) NULL DEFAULT NULL,
  `treceADiecisiete` VARCHAR(45) NULL DEFAULT NULL,
  `Deporte_idDeportes` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idsuperateIntercolegiados`),
  INDEX `fk_superateIntercolegiados_Deporte1_idx` (`Deporte_idDeportes` ASC),
  CONSTRAINT `fk_superateIntercolegiados_Deporte1`
    FOREIGN KEY (`Deporte_idDeportes`)
    REFERENCES `imdera`.`deporte` (`idDeportes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imdera`.`Eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`Eventos` (
  `idEventos` INT NOT NULL,
  `tipoEvento` VARCHAR(45) NULL,
  `lugar` VARCHAR(100) NULL,
  `dia` DATE NULL,
  `comuna` VARCHAR(45) NULL,
  `total` INT NULL,
  `nivel` VARCHAR(45) NULL,
  `observaciones` VARCHAR(500) NULL,
  PRIMARY KEY (`idEventos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdera`.`motor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdera`.`motor` (
  `idmotor` INT NOT NULL,
  `capacidadCondicional` VARCHAR(45) NULL,
  `resultado` VARCHAR(45) NULL,
  `valoracion` VARCHAR(45) NULL,
  `datosmorfo_idDatosMorfo` INT(11) NOT NULL,
  PRIMARY KEY (`idmotor`),
  INDEX `fk_motor_datosmorfo1_idx` (`datosmorfo_idDatosMorfo` ASC),
  CONSTRAINT `fk_motor_datosmorfo1`
    FOREIGN KEY (`datosmorfo_idDatosMorfo`)
    REFERENCES `imdera`.`datosmorfo` (`idDatosMorfo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
